import { ArrowRight, BarChart3, BrainCircuit, CheckCircle2, FileSearch, SearchCheck, ShieldCheck, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";

import { Button } from "@/components/ui/button";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { useAuth } from "@/hooks/useAuth";

const featureCards = [
  {
    icon: FileSearch,
    title: "Fake News Detection",
    description:
      "Paste a news article and get an AI-assisted prediction with confidence signals to help you decide whether it looks real or fake.",
    action: "Analyze news",
    path: "/#detect",
  },
  {
    icon: BrainCircuit,
    title: "AI Content Detection",
    description:
      "Check whether text was likely written by a human or generated by AI using the dedicated AI detector workspace.",
    action: "Try AI detector",
    path: "/ai-detector",
  },
  {
    icon: SearchCheck,
    title: "Source Cross Verification",
    description:
      "Compare claims against sources and supporting context so you can validate information before trusting or sharing it.",
    action: "Verify sources",
    path: "/cross-verify",
  },
  {
    icon: BarChart3,
    title: "Analytics Dashboard",
    description:
      "Review saved analysis history, compare model outputs, and turn investigation activity into clear visual insights.",
    action: "Open dashboard",
    path: "/dashboard",
  },
];

const steps = [
  "Choose the checker that matches your task.",
  "Paste content, claims, or source details into the workspace.",
  "Review the prediction, confidence, and supporting signals.",
  "Use the dashboard to track results and spot patterns over time.",
];

export default function UserLandingPage() {
  const navigate = useNavigate();
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <main>
        <section
          className="relative flex min-h-[100svh] items-center overflow-hidden pb-16 pt-28 sm:pt-32 lg:pb-20"
          style={{ background: "var(--gradient-hero)" }}
        >
          <div className="absolute inset-0 overflow-hidden" aria-hidden="true">
            <div className="absolute left-[10%] top-[18%] h-72 w-72 rounded-full bg-primary/20 blur-3xl animate-pulse-slow md:h-96 md:w-96" />
            <div className="absolute bottom-[12%] right-[8%] h-64 w-64 rounded-full bg-accent/20 blur-3xl animate-pulse-slow animation-delay-200 md:h-96 md:w-96" />
            <div className="absolute right-[36%] top-[46%] hidden h-56 w-56 rounded-full bg-secondary/20 blur-3xl animate-pulse-slow animation-delay-400 lg:block" />
            <div className="absolute inset-0 bg-[linear-gradient(rgba(79,70,229,0.035)_1px,transparent_1px),linear-gradient(90deg,rgba(79,70,229,0.035)_1px,transparent_1px)] bg-[size:60px_60px]" />
          </div>

          <div className="container relative z-10 mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid items-center gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:gap-16">
              <div className="space-y-7 text-center lg:text-left">
                <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-2 text-sm font-medium text-primary">
                  <Sparkles className="h-4 w-4" />
                  Your FakeCheck AI starting point
                </div>

                <div className="space-y-5">
                  <h1 className="mx-auto max-w-4xl text-4xl font-bold leading-tight tracking-tight sm:text-5xl xl:text-7xl lg:mx-0">
                    Welcome{user?.name ? `, ${user.name}` : ""}.
                    <span className="gradient-text block">What would you like to verify today?</span>
                  </h1>
                  <p className="mx-auto max-w-2xl text-base leading-7 text-muted-foreground sm:text-xl lg:mx-0">
                    Start with the right tool for your investigation. FakeCheck AI brings news detection,
                    AI-text detection, source verification, and analytics together in one secure workspace.
                  </p>
                </div>

                <div className="flex flex-col justify-center gap-3 sm:flex-row lg:justify-start">
                  <Button variant="hero" size="lg" onClick={() => navigate("/#detect")}>
                    Start with news detection
                    <ArrowRight className="h-5 w-5" />
                  </Button>
                  <Button variant="hero-outline" size="lg" onClick={() => navigate("/dashboard")}>
                    View analytics dashboard
                  </Button>
                </div>
              </div>

              <div className="glass-strong rounded-[2rem] p-6 shadow-2xl glow sm:p-8">
                <div className="mb-6 flex items-center gap-4">
                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-accent text-primary-foreground shadow-lg">
                    <ShieldCheck className="h-7 w-7" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-primary">How to use FakeCheck AI</p>
                    <h2 className="text-2xl font-bold tracking-tight">Simple verification flow</h2>
                  </div>
                </div>

                <div className="space-y-4">
                  {steps.map((step, index) => (
                    <div key={step} className="flex gap-4 rounded-2xl bg-background/60 p-4 shadow-sm">
                      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">
                        {index + 1}
                      </div>
                      <div className="flex items-start gap-3">
                        <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-success" />
                        <p className="text-sm leading-6 text-muted-foreground">{step}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="py-16 sm:py-20">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="mx-auto mb-10 max-w-3xl text-center">
              <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-2 text-sm font-medium text-primary">
                <ShieldCheck className="h-4 w-4" />
                Choose a tool
              </div>
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Everything you need to verify content</h2>
              <p className="mt-4 text-muted-foreground">
                Each feature has a focused workspace and a clear next step, so you can move from question to evidence quickly.
              </p>
            </div>

            <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
              {featureCards.map(({ icon: Icon, title, description, action, path }) => (
                <article key={title} className="glass hover-lift flex h-full flex-col rounded-3xl p-6 shadow-lg">
                  <div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                    <Icon className="h-6 w-6" />
                  </div>
                  <h3 className="text-xl font-semibold">{title}</h3>
                  <p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{description}</p>
                  <Button className="mt-6 w-full" variant="glass" onClick={() => navigate(path)}>
                    {action}
                    <ArrowRight className="h-4 w-4" />
                  </Button>
                </article>
              ))}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
